### ISSUE TITLE
google search result on mobile for neon looks odd

### ISSUE THREAD

**Issue by stepashka** [neondatabase/website#467] opened 2023-01-23 21:37 UTC
When searching on mobile, I see 4 times serverless postgres for neon.tech query. For the desktop it’s not the same and feels OK.

![Image](https://user-images.githubusercontent.com/445400/214155603-32bd6d8d-7a9c-4dc2-bfd9-0b376cc2677f.png)
![Image](https://user-images.githubusercontent.com/445400/214155602-68e7422a-fc13-4831-8e90-6ce1bd0b5abf.png)

submitted on behalf of @antonyc

**Comment by danieltprice** [comment] 2023-10-04 11:22
Closing. This issue does not seem to be occurring any longer. I get "Neon Tech" as the result on Android. Please reopen if the issue is still present on iOS.

**Closed by danieltprice** 2023-10-04 11:22 UTC
